config/routes.rb
IbmUnited::Application.routes.draw do
  root 'home#index'
  resources :user_sessions, only: [:create, :destroy] 
  resources :users, only: [:new, :create, :show]

  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout
  

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }
  validates :password, confirmation: true
  validates :password_confirmation, presence: true

  validates :email, uniqueness: true

  validates :first_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :require_login

  private 
  def not_authenticated
    redirect_to login_path, alert: "Please login first"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :require_login
  def index
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_filter :require_login, except: [:destroy]
  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password])
      redirect_back_or_to(root_path, notice: "Login successful")
    else
      flash.now[:alert] = "Login failed"
      render action: "new"
    end
  end

  def destroy
    logout 
    redirect_to(root_path, notice: "Logged out!")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :require_login, only: [:index, :new, :create]

  

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      auto_login(@user)
      # redirect_to(:action => "show", :id => @user.id , notice: 'User was successfully created')
      # login(@user.email, @user.password, remember_me = false)
      redirect_to( root_path, notice: "You're signed up and ready to fly!")
    else
      render action: 'new'
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def show
    # @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="small-12 columns banner-container">
  <div class="small-9 small-centered columns">
    <% if current_user %>
      <h1 class="name"><%= current_user.first_name %></h1>
      <h2><i class="fa fa-globe"></i></h2>
      <p>Thanks for flying with us today!</p>
      
      <h2>How can I help you?</h2>
      <h2><i class="fa fa-angle-double-down"></i></h2>
    <% else %>
      <h1 class="new-account"><i class="fa fa-globe"></i> United Airlines</h1>
      <p>Your Boarding Pass</p>
      <p>made mobile.</p>
    <% end %>
  </div>
</div>

<% if current_user %>
  <div class="small-12 columns boarding-pass">
    <div class="small-12 columns check-in">
      <h4><i class="fa fa-check-circle-o"></i> Check In </h4>
      <div class="small-12 columns boarding-pass-details">
        <h1>UA 2323</h1>
        <h5>TORONTO PEARSON INTL <i class="fa fa-arrow-right"></i> NYC LA GUARDIA</h5>
        <h5>Terminal 1 - Gate 12</h5>
        <div class="small-6 small-centered columns">
          <%= image_tag "qr_code.jpg" %>
        </div>
        <h1>Departs: 12:45 PM</h1>
        <h1>Arrives: 2:00 PM</h1>
      </div>
    </div>
  </div>
  <div class="small-12 columns flight-status">
    <div class="small-12 columns check-in">
      <h4><i class="fa fa-clock-o"></i> Flight Status</h4>
    </div>
  </div>
  <div class="small-12 columns book-a-flight">
    <div class="small-12 columns check-in">
      <h4><i class="fa fa-plane"></i> Book Flight</h4>
    </div>
  </div>
<% end %>
<%= render 'partials/nav' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "United Airlines | IBM Design" %></title>

    <%= stylesheet_link_tag    "application" %>
    <!-- google web fonts -->
    <link href='http://fonts.googleapis.com/css?family=Nixie+One|Montserrat:400,700' rel='stylesheet' type='text/css'>
    <!-- font-awesome icons -->
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
        
    <div>
      <div class="small-12 columns">
        <div class="small-6 small-centered columns">
          <% if flash[:notice] %>
            <p id="notice"><%= flash[:notice] %></p>
          <% end %>

          <% if flash[:alert] %>
            <p id="alert"><%= flash[:alert] %></p>
          <% end %>
          
          
        </div>
      </div>
      
      <%= yield %>      
    </div>
    
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/partials/_nav.html.erb
<div class="small-12 columns nav">
  <% if current_user %>
    <div class="logout">
      <%= link_to "Logout", logout_path, class: "logout-btn" %>
    </div>
  
    
  <% else %>
    <div class="small-6 small-centered columns login">
      <%= link_to "Login", login_path, class: "login-btn" %>  
    </div>
    <div class="small-6 small-centered columns sign-up">
      <%= link_to "Sign up", new_user_path, class: "sign-up-btn" %>  
    </div>
    
    
  <% end %>
</div>

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :class => "login-form", :method => :post do %>
  <div class="small-6 small-centered columns"><h3>Login</h3></div>
  <div class="small-12 columns">
    <%= label_tag :email, nil, class: "login-label" %>
  </div>
  <div class="small-5 small-centered columns">
    <%= text_field_tag :email %>
  </div>
  
  <div class="small-2 small-centered columns"><hr></div>

  <div class="small-12 columns">
    <%= label_tag :password, nil, class: "login-label" %>
  </div>
  <div class="small-5 small-centered columns">
    <%= password_field_tag :password %>
  </div>

  <div class="small-4 small-centered columns">
    <%= submit_tag "Login Now", class: "login-btn button expand" %>
  </div>
<% end %>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<div class="small-12 columns login-form">
  <%= render 'form' %>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>

  <div class="small-12 columns errors">
    <div class="small-10 small-centered columns">
      <% if @user.errors.any? %>
        <div id="error_explanation">
          <h4><i class="fa fa-exclamation-triangle"></i> <%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h4>

          <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
    </div>
  </div>

  <div class="create-new-account">
    <div class="small-12 columns">
      <%= f.label :first_name %>
      <div class="small-6 small-centered columns account-field"><%= f.text_field :first_name %></div>
    </div>

    <div class="small-12 columns">
      <%= f.label :email %>
      <div class="small-6 small-centered columns account-field">
        <%= f.text_field :email %>
      </div>
    </div>
    
    <div class="small-12 columns">
      <%= f.label :password %>
      <div class="small-6 small-centered columns account-field">
        <%= f.password_field :password %>
      </div>
    </div>
    
    <div class="small-12 columns">
      <%= f.label :password_confirmation %>
      <div class="small-6 small-centered columns account-field">
        <%= f.password_field :password_confirmation %>
      </div>
    </div>
    
    <div class="small-12 columns">
      <div class="small-5 small-centered columns"><%= f.submit "Create new account", class: "large button success expand" %>
      </div>
    </div>
  </div>

<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<div class="row">
  <div class="small-8 small-centered columns"><h1 class="new-account-title">Create New Account</h1></div>
</div>

<%= render 'form' %>

app/views/users/show.html.erb
<div class="small-12 columns banner-container">
  <div class="small-9 small-centered columns">
    <h1 class="new-account">
      <%= current_user.first_name %>
    </h1>
    <p>Your Boarding Pass</p>
    <p>made mobile.</p>
    <!-- <p><%= current_user.inspect %></p> -->
  </div>
</div>

<%= link_to "Logout", :logout, method: :post %>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>